namespace Jeffpardy
{
    public class Player
    {
        public string Team { get; set; }
        public string Name { get; set; }
        public string ConnectionId { get; set; }

        /// <summary>
        /// Durable identity for this player, stable across reconnects (which
        /// change the SignalR connection id). Generated by the client and
        /// persisted in localStorage, scoped to the game. Falls back to the
        /// connection id for older clients that don't supply one.
        /// </summary>
        public string PlayerId { get; set; }
    }

}
